### ISSUE TITLE
Add Message Token as field to Slack message

### ISSUE THREAD

**Issue by AmirSasson** [mgibas/serilog-sinks-slack#10]
today, only the Level and the Timestamp are hard coded sent to slack.
what if my log message look like this: 
`_logger.LogInformation("{ClientIp} has Joined", IP);`
i would expect to have another field ClientIp (the same as ElasticSerach Sink does).
any chance to have this in the next drop?

**Comment by TrapperHell** [comment]
This functionality is already present - at least at the time of writing. Considering that this request is very old, I am closing this for now.
