### ISSUE TITLE
Stacktrace field with too long message causes incorrect display

### ISSUE THREAD

**Issue by timotyweis** [mgibas/serilog-sinks-slack#12]
First of all thank you for the great sink.

I've used it and noticed that if the the stack trace of an exception is too long, the message gets cut and the formatting gets lost:  the texts starts with ``` but the matching end markdown is never reached (I see ...). Would it be possible to limit the message correctly in order to display the stack trace correctly formatted? It may even be interesting to have a max char configuration for this (since I don't know if this is configurable in Slack).

**Comment by mgibas** [comment]
Just found that Slack recommend max 4000 characters: https://api.slack.com/rtm

I would say that we can trim messages longer than that.

**Comment by TrapperHell** [comment]
This should now be resolved.
