### ISSUE TITLE
Sink not writing to Slack

### ISSUE THREAD

**Issue by djangohunt** [mgibas/serilog-sinks-slack#23]
I have used your sink in my application and it was working fine, it has now stopped working at all, I get no exception and nothing strange in Output (visual Studio).
I then tried your example application with my Webhook and that isn't working either, I have tested my Slack Webhook in Command Prompt and it is working fine. 
Is anyone else seeing this?

**Comment by markwkjr** [comment]
First time I've used this Sink, but I'm having the same problem. Not receiving any output in my Channel on Slack.

**Comment by TrapperHell** [comment]
This is a relatively old issue with very little contextual information. Here's hoping that the recently merged PR resolves this. Closing this in the mean time.

**Comment by GFoley83** [comment]
@djangohunt @markwkjr What did you do to resolve your issue? I'm having the same problem; I can use the webhook fine with Postman but with Serilog I get nothing.

**Comment by TrapperHell** [comment]
@GFoley83 are you using version 2.2.0?

This might be related to this issue: https://github.com/serilog-contrib/serilog-sinks-slack/issues/11

**Comment by GFoley83** [comment]
I am using framework 4.5.2 which I'm assuming is the root cause as I can't even get a console app working with it. 

I've tried different versions of Serilog with different versions of this sink but as of yet I haven't found the magic combination to make it work. Out of ideas now.

**Comment by TrapperHell** [comment]
Hi @GFoley83 I can confirm that I am able to reproduce your issue. To prevent cluttering this issue, I have opened up a new issue #40 . Thanks.

**Comment by TrapperHell** [comment]
Hi @GFoley83 if you could take the time to test the latest version (2.2.1) and confirm (on issue #40) that it's working for you now, that would be great. Thanks.
