### ISSUE TITLE
.Net Framework v 4.6 and NETStandard.Library

### ISSUE THREAD

**Issue by Leftyx** [mgibas/serilog-sinks-slack#9]
I was wondering why you're using NETStandard.Library for v.4.6 ?
I don't seem to be able to update the package for a solution ASP.NET MVC 4.6.

**Comment by mgibas** [comment]
@phnx47 do you know how we can solve this ?

**Comment by phnx47** [comment]
Yep, This is my bug, I will fix it tomorrow

**Comment by mgibas** [comment]
:+1:  thanks a lot

**Comment by phnx47** [comment]
It fixed in 1.2.51.
